package zgg.toolkit.system.mapper.autogen;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zgg.toolkit.system.model.entity.UserDetail;
import zgg.toolkit.system.model.entity.UserDetailExample;

public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    long countByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int deleteByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int insertSelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    List<UserDetail> selectByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    UserDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserDetail record, @Param("example") UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserDetail record, @Param("example") UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDetail record);
}