
server:
  port: 8200

#https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/htmlsingle/#boot-features-logging
logging:
  config: classpath:config/log4j2-spring.xml


spring:
  application:
    name: toolkit-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(Xhye9bypq1TuaCrsRH1AfW40fG54Ld3jOvCDdfhyPGCmul3dz/vqvxyth/JBDGG1vnENH2M5T8ohwCDrUlpAMeHvOANOaGF33+8C4Qc4ZhC8kIWrSMs38fONpfexxAjMiC7DkHJDyho=)
    username: ENC(Z0/JMfHi0wZIddTxjHR9ZA==)
    password: ENC(NCTQD5AjEwiJImFXRt8KBg4IHJjffI0nz2uBlHNnlRU=)
    druid:
      max-active: 5
      min-idle: 1
      max-wait: 10000
  rabbitmq:
    host: ENC(L9FqkAsdZH4r/TdQ1XlPb6yTi4i9XLHD)
    port: 5672
    username: ENC(nlsqMQVkglEe2eO31dGGeQ==)
    password: ENC(0G4dGHX9PBTSq9ge4q0h1/SWY7CchlRAVYKHXoDFjZ4=)

# 解密密匙
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}


#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: test-consumer-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer




mybatis:
  # 这里使用classpath*,这样才能找到依赖模块system中resource下的xml等静态资源文件，否则会报 invalid bound statement (not found)异常
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/autogen/*.xml
  configuration:
    map-underscore-to-camel-case: true

