package zgg.toolkit.apitool.model.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table api_group
 */
public class ApiGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_group.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_group.project_id
     *
     * @mbg.generated
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_group.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    public ApiGroup(Long id, Long projectId, String name, Integer sort) {
        this.id = id;
        this.projectId = projectId;
        this.name = name;
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    public ApiGroup() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_group.id
     *
     * @return the value of api_group.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_group.id
     *
     * @param id the value for api_group.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_group.project_id
     *
     * @return the value of api_group.project_id
     *
     * @mbg.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_group.project_id
     *
     * @param projectId the value for api_group.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_group.name
     *
     * @return the value of api_group.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_group.name
     *
     * @param name the value for api_group.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_group.sort
     *
     * @return the value of api_group.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_group.sort
     *
     * @param sort the value for api_group.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}