package zgg.toolkit.apitool.model.entity;

import java.time.LocalDateTime;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table api_project
 */
public class ApiProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_project.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_project.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_project.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_project.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_project
     *
     * @mbg.generated
     */
    public ApiProject(Long id, String name, String note, LocalDateTime createTime) {
        this.id = id;
        this.name = name;
        this.note = note;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_project
     *
     * @mbg.generated
     */
    public ApiProject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_project.id
     *
     * @return the value of api_project.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_project.id
     *
     * @param id the value for api_project.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_project.name
     *
     * @return the value of api_project.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_project.name
     *
     * @param name the value for api_project.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_project.note
     *
     * @return the value of api_project.note
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_project.note
     *
     * @param note the value for api_project.note
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_project.create_time
     *
     * @return the value of api_project.create_time
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_project.create_time
     *
     * @param createTime the value for api_project.create_time
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}