package zgg.toolkit.apitool.mapper.autogen;

import org.apache.ibatis.annotations.Param;
import zgg.toolkit.apitool.model.entity.ApiDetail;
import zgg.toolkit.apitool.model.entity.ApiDetailExample;

import java.util.List;

public interface ApiDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    long countByExample(ApiDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int deleteByExample(ApiDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int insert(ApiDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int insertSelective(ApiDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    List<ApiDetail> selectByExample(ApiDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    ApiDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiDetail record, @Param("example") ApiDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiDetail record, @Param("example") ApiDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiDetail record);
}