package zgg.toolkit.apitool.mapper.autogen;

import org.apache.ibatis.annotations.Param;
import zgg.toolkit.apitool.model.entity.ApiGroup;
import zgg.toolkit.apitool.model.entity.ApiGroupExample;

import java.util.List;

public interface ApiGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    long countByExample(ApiGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int deleteByExample(ApiGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int insert(ApiGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int insertSelective(ApiGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    List<ApiGroup> selectByExample(ApiGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    ApiGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiGroup record, @Param("example") ApiGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiGroup record, @Param("example") ApiGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiGroup record);
}