package zgg.toolkit.apitool.mapper.autogen;

import org.apache.ibatis.annotations.Param;
import zgg.toolkit.apitool.model.entity.ApiHistory;
import zgg.toolkit.apitool.model.entity.ApiHistoryExample;

import java.util.List;

public interface ApiHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    long countByExample(ApiHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int deleteByExample(ApiHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int insert(ApiHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int insertSelective(ApiHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    List<ApiHistory> selectByExample(ApiHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    ApiHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiHistory record, @Param("example") ApiHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiHistory record, @Param("example") ApiHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiHistory record);
}