package zgg.toolkit.system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zgg.toolkit.system.model.entity.UserExtend;
import zgg.toolkit.system.model.entity.UserExtendExample;

public interface UserExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    long countByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int deleteByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int insert(UserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int insertSelective(UserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    List<UserExtend> selectByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    UserExtend selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserExtend record, @Param("example") UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserExtend record, @Param("example") UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserExtend record);
}