
server:
  port: 8200

logging:
  level:
    root: info
    zgg:
      toolkit:
        system:
          mapper: trace

spring:
  application:
    name: toolkit-system
  jackson:
    time-zone: GMT+8
#    date-formatDateTime: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(RWSJ2ARZqRWloeBPLriTeBgzt18frPzvIlmvKnIVQEC7BPAjQExVAV+a+/o8H5vO2+MYT32ckpZ4CvXc1Q1KCw==)
    username: ENC(q+53R50ivBCY12BjCd+q2Q==)
    password: ENC(oXU7/1OOrGzV8kgLblq331xKxsQpkJmud+XGJcMJeds=)
    druid:
      max-active: 5
      min-idle: 1
      max-wait: 10000
  rabbitmq:
    host: ENC(M7yLfyocKDQ7FISHt5JX3hJdNVzZWAdD)
    port: 5672
    username: ENC(OUyI70OSdHlT1bN9+MQYMA==)
    password: ENC(X7CEWdxIP/EOvNSZLqISMCsmuG4zE/TWLE/GcYmGK9o=)

# 解密密匙
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/autogen/*.xml
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true

