
server:
  port: 8200

logging:
  level:
    root: info
    zgg:
      toolkit:
        system:
          mapper: trace
    com:
      zaxxer:
      hikari: debug

spring:
  application:
    name: toolkit-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(Xhye9bypq1TuaCrsRH1AfW40fG54Ld3jOvCDdfhyPGCmul3dz/vqvxyth/JBDGG1vnENH2M5T8ohwCDrUlpAMeHvOANOaGF33+8C4Qc4ZhC8kIWrSMs38fONpfexxAjMiC7DkHJDyho=)
    username: ENC(Z0/JMfHi0wZIddTxjHR9ZA==)
    password: ENC(NCTQD5AjEwiJImFXRt8KBg4IHJjffI0nz2uBlHNnlRU=)
    druid:
      max-active: 5
      min-idle: 1
      max-wait: 10000

# 解密密匙
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/autogen/*.xml
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true

