
server:
  port: 8200

logging:
  level:
    root: info
    zgg:
      toolkit:
        system:
          mapper: trace
    com:
      zaxxer:
      hikari: debug

spring:
  application:
    name: toolkit-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.34.242:3306/toolkit?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: nNsWbmYS1PjsJoncMMYdz6KLcv+Ma3PzVM6fsYCKPEn6+hrHAfKUM9YZ1hgjWG4aOSw3IOmys3ipanxOy9nXTQ==
    druid:
      max-active: 5
      min-idle: 1
      max-wait: 10000
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKuawc+3wVgX7iWqHReV8zBE9b0JALbVTQiYMYHcUAxfOnQ9eQkW4L0/EmHsF0rrqNV2MXC48wXNloVJPJzQkqcCAwEAAQ==


mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/autogen/*.xml
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true


