package zgg.toolkit.system.model.entity;

import zgg.toolkit.system.enums.StatusEnum;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_module
 */
public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   顶级为 0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.module_code
     *
     * @mbg.generated
     */
    private String moduleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.status
     *
     * @mbg.generated
     */
    private StatusEnum status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbg.generated
     */
    public Module(Long id, Long pid, String moduleName, String moduleCode, String icon, Integer sort, StatusEnum status) {
        this.id = id;
        this.pid = pid;
        this.moduleName = moduleName;
        this.moduleCode = moduleCode;
        this.icon = icon;
        this.sort = sort;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbg.generated
     */
    public Module() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.id
     *
     * @return the value of sys_module.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.id
     *
     * @param id the value for sys_module.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.pid
     *
     * @return the value of sys_module.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.pid
     *
     * @param pid the value for sys_module.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.module_name
     *
     * @return the value of sys_module.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.module_name
     *
     * @param moduleName the value for sys_module.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.module_code
     *
     * @return the value of sys_module.module_code
     *
     * @mbg.generated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.module_code
     *
     * @param moduleCode the value for sys_module.module_code
     *
     * @mbg.generated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode == null ? null : moduleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.icon
     *
     * @return the value of sys_module.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.icon
     *
     * @param icon the value for sys_module.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.sort
     *
     * @return the value of sys_module.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.sort
     *
     * @param sort the value for sys_module.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.status
     *
     * @return the value of sys_module.status
     *
     * @mbg.generated
     */
    public StatusEnum getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.status
     *
     * @param status the value for sys_module.status
     *
     * @mbg.generated
     */
    public void setStatus(StatusEnum status) {
        this.status = status;
    }
}