package zgg.toolkit.system.model.entity;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_permission
 */
public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_name
     *
     * @mbg.generated
     */
    private String perName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_code
     *
     * @mbg.generated
     */
    private String perCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.module_id
     *
     * @mbg.generated
     */
    private Long moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public Permission(Long id, String perName, String perCode, Long moduleId) {
        this.id = id;
        this.perName = perName;
        this.perCode = perCode;
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public Permission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_name
     *
     * @return the value of sys_permission.per_name
     * @mbg.generated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_name
     *
     * @param perName the value for sys_permission.per_name
     * @mbg.generated
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_code
     *
     * @return the value of sys_permission.per_code
     * @mbg.generated
     */
    public String getPerCode() {
        return perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_code
     *
     * @param perCode the value for sys_permission.per_code
     * @mbg.generated
     */
    public void setPerCode(String perCode) {
        this.perCode = perCode == null ? null : perCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.module_id
     *
     * @return the value of sys_permission.module_id
     * @mbg.generated
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.module_id
     *
     * @param moduleId the value for sys_permission.module_id
     * @mbg.generated
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }
}