package zgg.toolkit.system.model.entity;

import zgg.toolkit.core.enums.StatusEnum;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_permission
 */
public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.module_code
     *
     * @mbg.generated
     */
    private String moduleCode;

    /**
     * Database Column Remarks:
     *   顶层模块值为 0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parent_module
     *
     * @mbg.generated
     */
    private String parentModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_name
     *
     * @mbg.generated
     */
    private String perName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_code
     *
     * @mbg.generated
     */
    private String perCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   enable disable
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.status
     *
     * @mbg.generated
     */
    private StatusEnum status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public Permission(Long id, String moduleName, String moduleCode, String parentModule, String perName, String perCode, String icon, Integer sort, StatusEnum status) {
        this.id = id;
        this.moduleName = moduleName;
        this.moduleCode = moduleCode;
        this.parentModule = parentModule;
        this.perName = perName;
        this.perCode = perCode;
        this.icon = icon;
        this.sort = sort;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public Permission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.module_name
     *
     * @return the value of sys_permission.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.module_name
     *
     * @param moduleName the value for sys_permission.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.module_code
     *
     * @return the value of sys_permission.module_code
     *
     * @mbg.generated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.module_code
     *
     * @param moduleCode the value for sys_permission.module_code
     *
     * @mbg.generated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode == null ? null : moduleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parent_module
     *
     * @return the value of sys_permission.parent_module
     *
     * @mbg.generated
     */
    public String getParentModule() {
        return parentModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parent_module
     *
     * @param parentModule the value for sys_permission.parent_module
     *
     * @mbg.generated
     */
    public void setParentModule(String parentModule) {
        this.parentModule = parentModule == null ? null : parentModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_name
     *
     * @return the value of sys_permission.per_name
     *
     * @mbg.generated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_name
     *
     * @param perName the value for sys_permission.per_name
     *
     * @mbg.generated
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_code
     *
     * @return the value of sys_permission.per_code
     *
     * @mbg.generated
     */
    public String getPerCode() {
        return perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_code
     *
     * @param perCode the value for sys_permission.per_code
     *
     * @mbg.generated
     */
    public void setPerCode(String perCode) {
        this.perCode = perCode == null ? null : perCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.icon
     *
     * @return the value of sys_permission.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.icon
     *
     * @param icon the value for sys_permission.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sort
     *
     * @return the value of sys_permission.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sort
     *
     * @param sort the value for sys_permission.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.status
     *
     * @return the value of sys_permission.status
     *
     * @mbg.generated
     */
    public StatusEnum getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.status
     *
     * @param status the value for sys_permission.status
     *
     * @mbg.generated
     */
    public void setStatus(StatusEnum status) {
        this.status = status;
    }
}