package zgg.toolkit.system.model.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.modele_code
     *
     * @mbg.generated
     */
    private String modeleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.module_path
     *
     * @mbg.generated
     */
    private String modulePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_name
     *
     * @mbg.generated
     */
    private String perName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_code
     *
     * @mbg.generated
     */
    private String perCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public Permission(Long id, Long pid, String moduleName, String modeleCode, String modulePath, String perName, String perCode, String icon, Integer sort, String status) {
        this.id = id;
        this.pid = pid;
        this.moduleName = moduleName;
        this.modeleCode = modeleCode;
        this.modulePath = modulePath;
        this.perName = perName;
        this.perCode = perCode;
        this.icon = icon;
        this.sort = sort;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public Permission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.pid
     *
     * @return the value of sys_permission.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.pid
     *
     * @param pid the value for sys_permission.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.module_name
     *
     * @return the value of sys_permission.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.module_name
     *
     * @param moduleName the value for sys_permission.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.modele_code
     *
     * @return the value of sys_permission.modele_code
     *
     * @mbg.generated
     */
    public String getModeleCode() {
        return modeleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.modele_code
     *
     * @param modeleCode the value for sys_permission.modele_code
     *
     * @mbg.generated
     */
    public void setModeleCode(String modeleCode) {
        this.modeleCode = modeleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.module_path
     *
     * @return the value of sys_permission.module_path
     *
     * @mbg.generated
     */
    public String getModulePath() {
        return modulePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.module_path
     *
     * @param modulePath the value for sys_permission.module_path
     *
     * @mbg.generated
     */
    public void setModulePath(String modulePath) {
        this.modulePath = modulePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_name
     *
     * @return the value of sys_permission.per_name
     *
     * @mbg.generated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_name
     *
     * @param perName the value for sys_permission.per_name
     *
     * @mbg.generated
     */
    public void setPerName(String perName) {
        this.perName = perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_code
     *
     * @return the value of sys_permission.per_code
     *
     * @mbg.generated
     */
    public String getPerCode() {
        return perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_code
     *
     * @param perCode the value for sys_permission.per_code
     *
     * @mbg.generated
     */
    public void setPerCode(String perCode) {
        this.perCode = perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.icon
     *
     * @return the value of sys_permission.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.icon
     *
     * @param icon the value for sys_permission.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sort
     *
     * @return the value of sys_permission.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sort
     *
     * @param sort the value for sys_permission.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.status
     *
     * @return the value of sys_permission.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.status
     *
     * @param status the value for sys_permission.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}