package zgg.toolkit.system.model.entity;

public class UserExtend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_extend.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_extend.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    public UserExtend(Long userId, String realName) {
        this.userId = userId;
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_extend
     *
     * @mbg.generated
     */
    public UserExtend() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_extend.user_id
     *
     * @return the value of sys_user_extend.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_extend.user_id
     *
     * @param userId the value for sys_user_extend.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_extend.real_name
     *
     * @return the value of sys_user_extend.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_extend.real_name
     *
     * @param realName the value for sys_user_extend.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }
}