package zgg.toolkit.system.model.entity;

import java.time.LocalDate;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user_detail
 */
public class UserDetail {
    /**
     * Database Column Remarks:
     *   该值与sys_user的id一致
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_detail.birthday
     *
     * @mbg.generated
     */
    private LocalDate birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.id
     *
     * @return the value of sys_user_detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.id
     *
     * @param id the value for sys_user_detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.real_name
     *
     * @return the value of sys_user_detail.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.real_name
     *
     * @param realName the value for sys_user_detail.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_detail.birthday
     *
     * @return the value of sys_user_detail.birthday
     *
     * @mbg.generated
     */
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_detail.birthday
     *
     * @param birthday the value for sys_user_detail.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }
}